[project]
authors = ["Dakoro <david.korobetski@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "experiments"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
python = ">=3.11,<3.13"
pygame = ">=2.6.1,<3"
